/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Home;
import View.BuyerRegisterPage;
import View.SellerRegisterPage;

public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        youAreLabel = new javax.swing.JLabel();
        buyerButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        sellerButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        youAreLabel.setFont(new java.awt.Font("Serif", 0, 30)); // NOI18N
        youAreLabel.setText("I want to be Regestered as,");
        youAreLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 294, 0, 278);
        getContentPane().add(youAreLabel, gridBagConstraints);

        buyerButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buyerButton.setText("A Buyer");
        buyerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 396, 0, 0);
        getContentPane().add(buyerButton, gridBagConstraints);

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(67, 367, 66, 0);
        getContentPane().add(backButton, gridBagConstraints);

        sellerButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sellerButton1.setText("A Seller ");
        sellerButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sellerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellerButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 396, 0, 0);
        getContentPane().add(sellerButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerButtonActionPerformed
        // Create an instance of BuyerRegisterPage
        BuyerRegisterPage buyerRegisterPage = new BuyerRegisterPage();
    
        // Set the current window/form to be invisible (optional)
        this.setVisible(false);
    
        // Set BuyerRegisterPage to be visible
        buyerRegisterPage.setVisible(true);
    }//GEN-LAST:event_buyerButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        Home homePage = new Home();
        // Set the homePage to be visible
        homePage.setVisible(true);
        // Close the current frame
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void sellerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellerButton1ActionPerformed
        SellerRegisterPage sellerRegisterPage = new SellerRegisterPage();
    
        // Set the current window/form to be invisible (optional)
        this.setVisible(false);
    
        // Set BuyerRegisterPage to be visible
        sellerRegisterPage.setVisible(true);
    }//GEN-LAST:event_sellerButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buyerButton;
    private javax.swing.JButton sellerButton1;
    private javax.swing.JLabel youAreLabel;
    // End of variables declaration//GEN-END:variables
}
